<a href="https://colab.research.google.com/github/robruenes/killaudio/blob/main/ch_03/ch_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing Numpy Arrays in Python

The audio files we'll be reading and writing are going to be represented as numpy arrays and not regular Python list objects, so we explicitly create numpy arrays in the examples below to show how indexing works.

For more detail than included here, check out the 
[official numpy documentation](https://numpy.org/doc/stable/user/basics.indexing.html) for indexing.

In [4]:
# Install and import the numpy dependency.
!pip install numpy
import numpy as np


## One Dimensional Arrays

In [5]:
# Represent a vector as a one-dimensional numpy array from a Python list.
v = np.array([20, 21, 22, 23, 24, 25])


In [7]:
v[0] # First element

20

In [8]:
v[-1] # Last element, equivalent to V(end) in Matlab.

25

In [10]:
v[1] = 31 # Change the second element.
v[1]

31

## N-Dimensional Arrays

In [11]:
# Represent a 3 x 2 matrix using a numpy array from Python lists.
m = np.array([[11, 12], [13, 14], [15, 16]])

m[0][-1] # Last element in the first row.

12

In [12]:
m[-1][1] # Second element in the last row

16

In [13]:
# Set the element in the last column of the last row to 100
m[-1][-1] = 100 
m[-1][-1]

100

In [14]:
# N-dimensional indexing doesn't require use of brackets
# for each dimension.
m[-1, -1]

100

In [15]:
# The entire matrix.
m

array([[ 11,  12],
       [ 13,  14],
       [ 15, 100]])

In [16]:
# Another way of addressing the entire matrix.
m[:]

array([[ 11,  12],
       [ 13,  14],
       [ 15, 100]])

In [21]:
# Obtain the dimensions of the matrix
# Note: you can also assign to this member variable
# to change the shape.
m.shape

(3, 2)

## Slicing

*Note*: If you run into unexpected behavior down the road, check out the [numpy documentation](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding) for some important info regarding views and copies of the underlying array.

In [25]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Beginning from the second item (index 1),
# and ending at the eighth item (index 7),
# step across elements by increments of 2 
# and return those elements.
x[1:7:2] 

array([1, 3, 5])

In [30]:
# Equivalent expressions
x[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[2:10:1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Using negative indexing.
x[-2:10]

array([8, 9])

In [33]:
# Stepping in reverse.
x[7:3:-1]

array([7, 6, 5, 4])

In [35]:
# Equivalent to the above using -3 in place of 7.
x[-3:3:-1]

array([7, 6, 5, 4])

In [38]:
# Equivalent expressions
x[5:]

array([5, 6, 7, 8, 9])

In [39]:
x[5:10]

array([5, 6, 7, 8, 9])

In [42]:
# 3-dimensional array
x = np.array([[[1],[2],[3]], [[4], [5], [6]]])
x.shape

(2, 3, 1)

In [46]:
# If the # of objects is < N for an N dimensional array,
# ":" is assumed for any subsequent dimensions. You can
# see this via the equivalent expressions below.
x[1:2:]

array([[[4],
        [5],
        [6]]])

In [47]:
x[1:2]

array([[[4],
        [5],
        [6]]])


## Additional ways to create numpy arrays



In [48]:
# Create a vector of increasing terms.
vec1 = np.arange(6, 10)
vec1

array([6, 7, 8, 9])

In [ ]:
vec2 = np.arange(-4, 3)
vec2


In [54]:
# Increase by increments of 2
vec3 = np.arange(1,11,2)
vec3

array([1, 3, 5, 7, 9])

In [55]:
vec4 = np.arange(1, 10, 2)
vec4

array([1, 3, 5, 7, 9])

In [56]:
# Clear demonstration that the interval created
# is [start, stop) (in other words, exclude the stop).
vec5 = np.arange(1,3,2)
vec5

array([1])

In [57]:
vec6 = np.arange(3, 1, -1)
vec6

array([3, 2])

In [58]:
# Using the linspace function to create a linearly spaced array,
# with parameters start, stop and an optional number of samples to generate.
vec7 = np.linspace(10, 14, 5)
vec7

array([10., 11., 12., 13., 14.])

In [59]:
vec8 = np.linspace(10, 13, 5)
vec8

array([10.  , 10.75, 11.5 , 12.25, 13.  ])

In [60]:
vec9 = np.linspace(13, 10, 5)
vec9

array([13.  , 12.25, 11.5 , 10.75, 10.  ])

In [61]:
vec10 = np.linspace(0, 100, 5)
vec10

array([  0.,  25.,  50.,  75., 100.])

In [67]:
# Logarithmically spaced vectors. By default, the base is 10. The call
# below creates a vector of 10 elements, spaced evenly on a log scale
# between 10^0 and 10^2.
vec11 = np.logspace(0, 2, 10)
vec11

array([  1.        ,   1.66810054,   2.7825594 ,   4.64158883,
         7.74263683,  12.91549665,  21.5443469 ,  35.93813664,
        59.94842503, 100.        ])

In [68]:
vec12 = np.logspace(1,4,20)
vec12

array([   10.        ,    14.38449888,    20.69138081,    29.76351442,
          42.81332399,    61.58482111,    88.58667904,   127.42749857,
         183.29807108,   263.66508987,   379.26901907,   545.55947812,
         784.75997035,  1128.83789168,  1623.77673919,  2335.72146909,
        3359.81828628,  4832.93023857,  6951.92796178, 10000.        ])


## Numpy arrays with predefined values


In [73]:
np.ones([3,1])

array([[1.],
       [1.],
       [1.]])

In [71]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy array transposition

In [75]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [76]:
transposed_x = np.transpose(x)
transposed_x

array([1, 2, 3])

In [78]:
w = np.array([[1, 2, 3], [4, 5, 6]])
w

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
transposed_w = np.transpose(w)
transposed_w

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dimensions of numpy arrays

In [80]:
x = np.ones([3, 2])
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
# Calling shape gives you information about the dimensions
# of the numpy array.
x.shape

(3, 2)

In [84]:
# In this case, number of rows
x.shape[0]

3

In [85]:
# Number of columns
x.shape[1]

2

In [87]:
# Calculate how many dimensions the array is
len(x.shape)

2