<a href="https://colab.research.google.com/github/robruenes/killaudio/blob/main/ch_03/ch_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing Numpy Arrays in Python

The audio files we'll be reading and writing are going to be represented as numpy arrays and not regular Python list objects, so we explicitly create numpy arrays in the examples below to show how indexing works.

For more detail than included here, check out the 
[official numpy documentation](https://numpy.org/doc/stable/user/basics.indexing.html) for indexing.

In [4]:
# Install and import the numpy dependency.
!pip install numpy
import numpy as np


## One Dimensional Arrays

In [5]:
# Represent a vector as a one-dimensional numpy array from a Python list.
v = np.array([20, 21, 22, 23, 24, 25])


In [7]:
v[0] # First element

20

In [8]:
v[-1] # Last element, equivalent to V(end) in Matlab.

25

In [10]:
v[1] = 31 # Change the second element.
v[1]

31

## N-Dimensional Arrays

In [11]:
# Represent a 3 x 2 matrix using a numpy array from Python lists.
m = np.array([[11, 12], [13, 14], [15, 16]])

m[0][-1] # Last element in the first row.

12

In [12]:
m[-1][1] # Second element in the last row

16

In [13]:
# Set the element in the last column of the last row to 100
m[-1][-1] = 100 
m[-1][-1]

100

In [14]:
# N-dimensional indexing doesn't require use of brackets
# for each dimension.
m[-1, -1]

100

In [15]:
# The entire matrix.
m

array([[ 11,  12],
       [ 13,  14],
       [ 15, 100]])

In [16]:
# Another way of addressing the entire matrix.
m[:]

array([[ 11,  12],
       [ 13,  14],
       [ 15, 100]])

In [21]:
# Obtain the dimensions of the matrix
# Note: you can also assign to this member variable
# to change the shape.
m.shape

(3, 2)

## Slicing

*Note*: If you run into unexpected behavior down the road, check out the [numpy documentation](https://numpy.org/doc/stable/user/basics.indexing.html#slicing-and-striding) for some important info regarding views and copies of the underlying array.

In [25]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Beginning from the second item (index 1),
# and ending at the eighth item (index 7),
# step across elements by increments of 2 
# and return those elements.
x[1:7:2] 

array([1, 3, 5])

In [30]:
# Equivalent expressions
x[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[2:10:1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Using negative indexing.
x[-2:10]

array([8, 9])

In [33]:
# Stepping in reverse.
x[7:3:-1]

array([7, 6, 5, 4])

In [35]:
# Equivalent to the above using -3 in place of 7.
x[-3:3:-1]

array([7, 6, 5, 4])

In [38]:
# Equivalent expressions
x[5:]

array([5, 6, 7, 8, 9])

In [39]:
x[5:10]

array([5, 6, 7, 8, 9])

In [42]:
# 3-dimensional array
x = np.array([[[1],[2],[3]], [[4], [5], [6]]])
x.shape

(2, 3, 1)

In [46]:
# If the # of objects is < N for an N dimensional array,
# ":" is assumed for any subsequent dimensions. You can
# see this via the equivalent expressions below.
x[1:2:]

array([[[4],
        [5],
        [6]]])

In [47]:
x[1:2]

array([[[4],
        [5],
        [6]]])